version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(message)s"
handlers:
  file:
    level: INFO
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: ""
    maxBytes: 52428800
    backupCount: 1
loggers:
  navigation_logger:
    level: INFO
    handlers: [file]
    propagate: no
